image: python:3

stages:
  - release

Attach versioned zip to release:
  stage: release
  script:
    - pip3 install gitlab-release
    - gitlab-release --zip "sddm-eucalyptus-drop-${CI_COMMIT_TAG}.zip" *
  only:
    - tags
